version: '3.8'
services:
  php-apache-environment:
    container_name: webserver
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - database-environment
    volumes:
      - ./app:/var/www/html/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - 8000:80
  database-environment:
    container_name: database
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - "9906:3306"
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    ports:
        - '8008:80'
    restart: always
    environment:
        PMA_HOST: database
    depends_on:
        - database-environment